get_version_retries = 2
ping_retries = 2
ping_timeout = 3 # Seconds
scan_threads = 300
config_threads = 300
reboot_threads = 300


### IMPORTANT ###
# You need to change the password of the miners using the whatsminer
# tool or the privileged API will not work using admin as the password.
# If you change the password, you can pass that password here.

whatsminer_pwd = "admin"

### DEBUG MODE ###
# change this to debug = true
# to enable debug mode.
debug = false
# debug = true
